# Generated by Django 2.0.3 on 2018-03-30 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
